# Site settings
author: Peter Toth
title: Peter Tóth | web developer
email: peter@petertoth.me
description: Personal website & blog about web development mainly in Ruby on Rails
keywords: web, development, design, programming, code, coding, rails, ruby, css, sass, stylesheet, javascript, blog, github
baseurl: ""
root: /
url: "http://petertoth.me"
twitter_username: yednorozec
github_username:  petertoth

# Build settings
markdown: kramdown
permalink: /:title
